# Generated by Django 5.1.6 on 2025-03-06 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('gmail', models.EmailField(max_length=250, unique=True)),
                ('phone', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('gmail', models.EmailField(max_length=250, unique=True)),
                ('phone', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('confirmedStudents', models.IntegerField(default=0)),
                ('timeGoing', models.TimeField()),
                ('timeBack', models.TimeField()),
                ('duration', models.IntegerField(default=0)),
                ('duration_measurement', models.CharField(choices=[('h', 'hour'), ('m', 'minute')], default='m', max_length=2)),
                ('is_going_started', models.BooleanField(default=False)),
                ('is_going_finished', models.BooleanField(default=False)),
                ('is_back_started', models.BooleanField(default=False)),
                ('is_back_finished', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transport.institution')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=150)),
                ('plate', models.CharField(max_length=7)),
                ('capacityStudents', models.IntegerField()),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='transport.driver')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus', to='transport.route')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Bus',
            },
        ),
        migrations.CreateModel(
            name='StudentRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onbus', models.BooleanField(default=False)),
                ('going', models.BooleanField()),
                ('back', models.BooleanField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentRoutes', to='transport.route')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentRoutes', to='transport.student')),
            ],
            options={
                'verbose_name': 'Student Route',
                'verbose_name_plural': 'Student Routes',
            },
        ),
    ]
