# Generated by Django 5.1.6 on 2025-03-02 18:06

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bus',
        ),
        migrations.AddField(
            model_name='route',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='duration_measurement',
            field=models.CharField(choices=[('h', 'hour'), ('m', 'minute')], default='m', max_length=2),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='drivers/'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='photo',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='institutions/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='students/'),
        ),
        migrations.CreateModel(
            name='StudentRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('going', models.BooleanField()),
                ('back', models.BooleanField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentRoutes', to='transport.route')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentRoutes', to='transport.student')),
            ],
            options={
                'verbose_name': 'Student Route',
                'verbose_name_plural': 'Student Routes',
            },
        ),
    ]
