# Generated by Django 5.1.6 on 2025-03-02 21:03

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_remove_student_bus_route_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(null=True, storage=storages.backends.s3.S3Storage(), upload_to='students/'),
        ),
    ]
