# Generated by Django 5.1.6 on 2025-03-03 04:36

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='transport.route'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='gmail',
            field=models.EmailField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(null=True, storage=storages.backends.s3.S3Storage(), upload_to='drivers/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gmail',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
