# Generated by Django 5.1.6 on 2025-03-03 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_bus_route_alter_driver_gmail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transport.institution'),
        ),
    ]
