# Generated by Django 5.1.6 on 2025-03-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_route_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.CharField(default='descricao padrao', max_length=250),
            preserve_default=False,
        ),
    ]
