# Generated by Django 5.1.6 on 2025-03-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_route_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(default='nome descritivo', max_length=100),
            preserve_default=False,
        ),
    ]
