# Generated by Django 5.1.6 on 2025-03-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_route_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='confirmedStudents',
            field=models.IntegerField(default=0),
        ),
    ]
