# Generated by Django 5.1.6 on 2025-03-05 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_route_confirmedstudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentroute',
            name='onbus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='transport.route'),
        ),
    ]
