# Generated by Django 5.1.6 on 2025-03-05 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_studentroute_onbus_alter_bus_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transport.institution'),
        ),
    ]
