# Generated by Django 5.1.6 on 2025-03-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_alter_route_institution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='back',
            new_name='timeBack',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='going',
            new_name='timeGoing',
        ),
        migrations.AddField(
            model_name='route',
            name='is_back_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='is_back_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='is_going_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='is_going_started',
            field=models.BooleanField(default=False),
        ),
    ]
