# Generated by Django 5.1.6 on 2025-03-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_rename_back_route_timeback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
