# Generated by Django 5.1.6 on 2025-03-06 01:18

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_alter_driver_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(null=True, storage=storages.backends.s3.S3Storage(), upload_to='drivers/'),
        ),
    ]
