# Generated by Django 5.1.6 on 2025-03-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0014_alter_bus_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
    ]
